apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    role: recording-rules
  name: containerresourceusage
  namespace: monitoring
spec:
  groups:
    - name: requests
      rules:
        # 7d metrics
        - record: container_average_cpu_1d
          expr: |
            avg_over_time(
              node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate[1d]
            )
        - record: container_average_memory_1d
          expr: |
            avg_over_time(
              container_memory_working_set_bytes[1d]
            )
